:Author: Shutdown
:Email: {AuthorEmail}
:Date: 28/03/2020
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 linkeDisplay             => Arduino sketch folder
  ├── linkeDisplay.ino    => main Arduino file
  ├── ../circuit.png      => (optional) an image of the required schematics
  ├── ../upView.jpg       => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact Shutdown https://id.arduino.cc/Shutdown

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 220 Resistor   | 1234-abcd   | 1
| L1 | LCD Screen     | 2345-asdf   | 1
| R2 | 10K Potentio   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
